name: Release

on: push

jobs:
  release_osx:
    name: Release for OSX
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: package
        run: npm run package:osx
      - name: publish
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          files: |
            package/*.dmg
